spring:
  application:
    name: studygraphql

  h2:
    console:
      enabled: true

  datasource:
    generate-unique-name: true
    url: jdbc:h2:mem:studygraphql
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true

  graphql:
    graphiql:
      enabled: true
