spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}

  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_URI}